### ISSUE TITLE
Executor doesn't support recent CUDA capabilities

### ISSUE THREAD

**Issue by freddyheppell** [jina-ai/executor-text-transformers-torch-encoder#13]
When I try and use this executor on a compute server with an RTX 3090, I get the following warning:

```
executor0_1  | NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
executor0_1  | The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
```

I'm using the `latest-gpu` tag of the executor, inside a Docker container, from running `jina export docker-compose` on this flow:

```yml
jtype: Flow
executors:
  - uses: 'jinahub+docker://TransformerTorchEncoder/latest-gpu'
    uses_with:
      pretrained_model_name_or_path: 'sentence-transformers/distiluse-base-multilingual-cased-v2'
      device: cuda
    gpus: 1
```
